  data <- read.csv("../household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
  bar <- subset(data, (Date=="1/2/2007") | (Date=="2/2/2007"))
  png ("plot1.png", width=480, height=480)
  hist(bar$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", col="red")
  dev.off()
